apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 8.5.1
    chart: prometheus-operator
    helm:
      parameters:
        - name: prometheus.prometheusSpec.resources.requests.cpu
          value: '1'
        - name: prometheus.prometheusSpec.resources.requests.memory
          value: '2Gi'
        - name: prometheus.prometheusSpec.resources.limits.cpu
          value: '1'
        - name: prometheus.prometheusSpec.resources.limits.memory
          value: '4Gi'
        - name: prometheus.prometheusSpec.replicas
          value: '2'
        - name: kubelet.serviceMonitor.https
          value: 'false'
        - name: grafana.additionalDataSources[0].name
          value: "Loki"
        - name: grafana.additionalDataSources[0].type
          value: "loki"
        - name: grafana.additionalDataSources[0].url
          value: "http://distributor"
        - name: grafana.additionalDataSources[0].access
          value: "proxy"
        - name: grafana.grafana\.ini.auth\.anonymous.enabled
          value: "true"
        - name: grafana.grafana\.ini.auth\.anonymous.org_role
          value: "Editor"
        - name: grafana.plugins[0]
          value: "grafana-piechart-panel"
        - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
          value: "false"
        - name: alertmanager.enabled
          value: "false"
        - name: "prometheusOperator.admissionWebhooks.patch.image.tag"
          value: "v1.2.0"
  project: monitoring
  syncPolicy:
    automated: {}
